DIRS = \
  Alone\~ \
  Alone7z\~ \
  Fm\~ \
  Format7z\~ \
  Format7zF\~ \
  Format7zR\~ \
  Format7zExtract\~ \
  Format7zExtractR\~ \
  
all: $(DIRS)

$(DIRS):
!include "../SubBuild.mak"
